version: "3.8"
services:
  db:
    container_name: postgres_container
    image: postgres:14.1-alpine
    restart: always

    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=ecommerce
    ports:
      - "9254:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./:/docker-entrypoint-initdb.d

  pg_admin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:6
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@email.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - "5050:5050"

volumes:
  pg_data:
